version: "3.9"

services:
  rpgsessions_db:
    image: postgres:11
    container_name: rpgsessions_db
    restart: always
    networks:
      db_net:
        ipv4_address: ${IP_POSA_POSTGRES}
    expose:
      - "5432"
    volumes:
      - dbvol:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: rpgsessions
      POSTGRES_USER: rpgsessions
      POSTGRES_PASSWORD_FILE: /run/secrets/rpgsessions_db_password
    secrets:
      - rpgsessions_db_password
    user: postgres:postgres

  rpgsessions_rabbit:
    image: rabbitmq:3
    expose:
      - "5672"
    container_name: rpgsessions_rabbit
    networks:
      rabbit_net:
        ipv4_address: ${IP_RABA_RABBIT}

  rpgsessions_redis:
    build:
      context: ${CONTEXT_PATH}
      dockerfile: ${DOCKER_PATH}redis/Dockerfile
    container_name: rpgsessions_redis
    expose:
      - "6379"
    volumes:
#      - redisvol:/usr/local/etc/redis/
#      - /docker/host/dir:/data
      - redisvol:/data
    networks:
      redis_net:
        ipv4_address: ${IP_REDA_REDIS}

  rpgsessions_web:
    build:
      context: ${CONTEXT_PATH}
      dockerfile: ${DOCKER_PATH}nginx/Dockerfile
    container_name: rpgsessions_web
    restart: always
#    environment:
#      IP_UPSTREAM: ${IP_NGIA_rpgsessions}
#      IP_SERVER: ${IP_NGIA_NGINX}
    ports:
      - "82:8000"
    networks:
      web_net:
        ipv4_address: ${IP_NGIA_NGINX}
    volumes:
      - appvol:/srv/

  rpgsessions_app:
    build:
      context: ${CONTEXT_PATH}
      dockerfile: ${DOCKER_PATH}rpgsessions/Dockerfile
    container_name: rpgsessions_app
    expose:
      - "8080"
    environment:
      DEBUG: ${rpgsessions_DEBUG}
      REDIS_BACKEND: ${IP_REDA_REDIS}
      RABBIT_BROKER: ${IP_RABA_RABBIT}
      DB_HOST: ${IP_POSA_POSTGRES}
      DB_NAME: cve_aggregation
      DB_USER: cve-aggregation
      SRV_DIR: "/srv"
      DB_PASSWORD_FILE: /run/secrets/rpgsessions_db_password
      DJANGO_SECRET_FILE: /run/secrets/django_secret
      rpgsessions_LOG: /var/log/rpgsessions/rpgsessions.log
      ALLOWED_HOSTS: '*'
#      CELERY_BROKER_URL: amqp://@${IP_RABA_RABBIT}
#      CELERY_RESULT_BACKEND: redis://${IP_REDA_REDIS}
    networks:
      db_net:
        ipv4_address: ${IP_POSA_rpgsessions}
      rabbit_net:
        ipv4_address: ${IP_RABA_rpgsessions}
      redis_net:
        ipv4_address: ${IP_REDA_rpgsessions}
      web_net:
        ipv4_address: ${IP_NGIA_rpgsessions}
    secrets:
      - rpgsessions_db_password
      - django_secret
    volumes:
      - appvol:/srv/
      - /sys/fs/cgroup/:/sys/fs/cgroup:ro
    depends_on:
      - rpgsessions_db
      - rpgsessions_redis
      - rpgsessions_rabbit
    privileged: true
    cap_add:
      - SYS_ADMIN

secrets:
    rpgsessions_db_password:
        file: ./secrets/rpgsessions_password.txt
    django_secret:
        file: ./secrets/django_secret_key.txt

volumes:
  dbvol:
    name: rpgsessions_db_vol
    external: true
  appvol:
    name: rpgsessions_srv_vol
    external: true
  redisvol:
    name: rpgsessions_redis_vol
    external: true

networks:
  db_net:
    name: rpgsessions_db_net
    ipam:
      driver: default
      config:
        - subnet: ${POSA_SUBNET}
          gateway: ${POSA_GATEWAY}
    driver_opts:
      com.docker.network.bridge.name: dbr-as_db

  rabbit_net:
    name: rpgsessions_rabbit_net
    ipam:
      driver: default
      config:
        - subnet: ${RABA_SUBNET}
          gateway: ${RABA_GATEWAY}
    driver_opts:
      com.docker.network.bridge.name: dbr-as_rabbit

  redis_net:
    name: rpgsessions_redis_net
    ipam:
      driver: default
      config:
        - subnet: ${REDA_SUBNET}
          gateway: ${REDA_GATEWAY}
    driver_opts:
      com.docker.network.bridge.name: dbr-as_redis

  web_net:
    name: rpgsessions_web_net
    ipam:
      driver: default
      config:
        - subnet: ${NGIA_SUBNET}
          gateway: ${NGIA_GATEWAY}
    driver_opts:
      com.docker.network.bridge.name: dbr-as_web
