version: "3.9"

services:
  rpgsessions_db:
    image: postgres:11
    container_name: rpgsessions_db
    restart: always
    networks:
      db_net:
        ipv4_address: ${IP_POSR_POSTGRES}
    expose:
      - "5432"
    volumes:
      - dbvol:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: rpgsessions
      POSTGRES_USER: rpgsessions
      POSTGRES_PASSWORD_FILE: /run/secrets/rpgsessions_db_password
    secrets:
      - rpgsessions_db_password
    user: postgres:postgres

  rpgsessions_web:
    build:
      context: ${CONTEXT_PATH}
      dockerfile: ${DOCKER_PATH}nginx/Dockerfile
    container_name: rpgsessions_web
    restart: always
    ports:
      - "85:8000"
    networks:
      web_net:
        ipv4_address: ${IP_NGIR_NGINX}
    volumes:
      - appvol:/srv/

  rpgsessions_app:
    build:
      context: ${CONTEXT_PATH}
      dockerfile: ${DOCKER_PATH}rpgsessions/Dockerfile
    container_name: rpgsessions_app
    expose:
      - "8080"
    environment:
      DEBUG: ${RPGSESSIONS_DEBUG}
      DB_HOST: ${IP_POSA_POSTGRES}
      DB_NAME: extraventures
      DB_USER: extraventures
      SRV_DIR: "/srv"
      DB_PASSWORD_FILE: /run/secrets/rpgsessions_db_password
      DJANGO_SECRET_FILE: /run/secrets/django_secret
      RPGSESSIONS_LOG: /var/log/rpgsessions/rpgsessions.log
      ALLOWED_HOSTS: '*'
    networks:
      db_net:
        ipv4_address: ${IP_POSR_RPGSESSIONS}
      web_net:
        ipv4_address: ${IP_NGIR_RPGSESSIONS}
    secrets:
      - rpgsessions_db_password
      - django_secret
    volumes:
      - appvol:/srv/
      - /sys/fs/cgroup/:/sys/fs/cgroup:ro
    depends_on:
      - rpgsessions_db
    privileged: true
    cap_add:
      - SYS_ADMIN

secrets:
    rpgsessions_db_password:
        file: ./secrets/rpgsessions_password.txt
    django_secret:
        file: ./secrets/django_secret_key.txt

volumes:
  dbvol:
    name: rpgsessions_db_vol
    external: true
  appvol:
    name: rpgsessions_srv_vol
    external: true

networks:
  db_net:
    name: rpgsessions_db_net
    ipam:
      driver: default
      config:
        - subnet: ${POSR_SUBNET}
          gateway: ${POSR_GATEWAY}
    driver_opts:
      com.docker.network.bridge.name: dbr-as_rpgdb

  web_net:
    name: rpgsessions_web_net
    ipam:
      driver: default
      config:
        - subnet: ${NGIR_SUBNET}
          gateway: ${NGIR_GATEWAY}
    driver_opts:
      com.docker.network.bridge.name: dbr-as_rpgweb
