# Generated by Django 4.0.3 on 2022-03-15 02:32

import colorfield.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('version', models.CharField(default='', max_length=32)),
                ('acronym', models.CharField(default='', max_length=6)),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('alpha', colorfield.fields.ColorField(default='#666666', image_field=None, max_length=18, samples=None)),
                ('beta', colorfield.fields.ColorField(default='#666666', image_field=None, max_length=18, samples=None)),
                ('gamma', colorfield.fields.ColorField(default='#666666', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('episode', models.PositiveIntegerField(default=1)),
                ('campaign', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('date_start', models.DateField(default=datetime.datetime.now)),
                ('time_start', models.TimeField(default=datetime.datetime.now)),
                ('duration', models.PositiveIntegerField(default=4)),
                ('mandatory_spots', models.PositiveIntegerField(default=4)),
                ('optional_spots', models.PositiveIntegerField(default=0)),
                ('newbies_allowed', models.BooleanField(default=True)),
                ('one_shot_adventure', models.BooleanField(default=True)),
                ('level', models.CharField(choices=[('0', 'Débutants'), ('1', 'Bas niveaux'), ('2', 'Niveaux intermédiaires'), ('3', 'Haut niveaux'), ('4', 'Chevronnés')], default='0', max_length=16)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.game')),
                ('mj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('realm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.realm')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=256)),
                ('presentation', models.TextField(blank=True, default='', max_length=2048)),
                ('need_drop', models.BooleanField(default=False)),
                ('can_drop', models.BooleanField(default=False)),
                ('realm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.realm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
