# Generated by Django 4.0.3 on 2022-03-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='session',
            name='level',
        ),
        migrations.RemoveField(
            model_name='session',
            name='newbies_allowed',
        ),
        migrations.RemoveField(
            model_name='session',
            name='one_shot_adventure',
        ),
    ]
