# Generated by Django 4.0.3 on 2022-03-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_session_campaign_session_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='newbies_allowed',
            field=models.BooleanField(default=True, verbose_name='noobs'),
        ),
        migrations.AlterField(
            model_name='session',
            name='one_shot_adventure',
            field=models.BooleanField(default=True, verbose_name='oneshot'),
        ),
    ]
