# Generated by Django 4.0.3 on 2022-03-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_session_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
