# Generated by Django 4.0.3 on 2022-03-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_session_newbies_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='campaign',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
