# Generated by Django 4.0.3 on 2022-03-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_availability_i_am_here_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='i_am_here_mode',
        ),
        migrations.AddField(
            model_name='availability',
            name='absent_mode',
            field=models.BooleanField(default=False),
        ),
    ]
