# Generated by Django 4.0.3 on 2022-03-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_remove_availability_i_am_here_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='date_pub',
            field=models.DateField(auto_now=True),
        ),
    ]
