# Generated by Django 4.0.3 on 2022-03-18 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_profile_alpha_profile_beta_profile_gamma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='mj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.profile'),
        ),
    ]
