# Generated by Django 4.0.3 on 2022-03-18 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_alter_inscription_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 5, 33, 38, 443179)),
        ),
    ]
