# Generated by Django 4.0.3 on 2022-03-18 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_alter_inscription_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 15, 7, 14, 378900)),
        ),
    ]
