# Generated by Django 4.0.3 on 2022-03-21 23:36

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_alter_availability_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='alpha',
            field=colorfield.fields.ColorField(default='#666666', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='campaign',
            name='beta',
            field=colorfield.fields.ColorField(default='#666666', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='campaign',
            name='gamma',
            field=colorfield.fields.ColorField(default='#666666', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 0, 36, 12, 547980)),
        ),
    ]
