# Generated by Django 4.0.3 on 2022-03-21 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_campaign_alpha_campaign_beta_campaign_gamma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='acronym',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 0, 46, 2, 12167)),
        ),
    ]
