# Generated by Django 4.0.3 on 2022-03-18 14:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_alter_inscription_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 15, 8, 9, 580980)),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(default=datetime.datetime(2022, 3, 18, 15, 8, 9, 581956))),
                ('date_pub', models.DateTimeField(default=datetime.datetime(2022, 3, 18, 15, 8, 9, 581977))),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.profile')),
            ],
        ),
    ]
