# Generated by Django 4.0.3 on 2022-03-22 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_campaign_acronym_campaign_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 1, 57, 31, 463081)),
        ),
    ]
