# Generated by Django 4.0.3 on 2022-03-22 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_alter_availability_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shield',
            field=models.CharField(default='gamemaster_shield', max_length=256),
        ),
        migrations.AddField(
            model_name='profile',
            name='silhouette',
            field=models.CharField(default='player', max_length=256),
        ),
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 22, 52, 58, 572889)),
        ),
    ]
