# Generated by Django 4.0.3 on 2022-03-22 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_profile_shield_profile_silhouette_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 1, 8, 27784)),
        ),
    ]
