# Generated by Django 4.0.3 on 2022-03-19 03:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0028_alter_availability_when_alter_inscription_date_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='max_episodes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 3, 19, 3, 52, 18, 574030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 3, 52, 18, 573401, tzinfo=utc)),
        ),
    ]
