# Generated by Django 4.0.3 on 2022-03-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0036_alter_inscription_date_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='wanted',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
