# Generated by Django 4.0.3 on 2022-03-24 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0041_alter_availability_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='place',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 23, 25, 39, 264959)),
        ),
    ]
