# Generated by Django 4.0.3 on 2022-03-29 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0052_alter_availability_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='mandatory_spots',
        ),
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 3, 29, 2, 56, 39, 311458)),
        ),
    ]
