# Generated by Django 4.0.3 on 2022-03-29 10:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0053_remove_session_mandatory_spots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.profile'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 3, 29, 12, 3, 0, 132367)),
        ),
    ]
