# Generated by Django 4.0.3 on 2022-03-30 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0062_alter_availability_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 3, 30, 13, 41, 2, 650661)),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_start',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
    ]
