# Generated by Django 4.0.3 on 2022-03-30 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0063_alter_availability_when_alter_session_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 3, 31, 0, 38, 33, 660676)),
        ),
    ]
