# Generated by Django 4.0.3 on 2022-04-02 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0068_profile_icon_style_profile_shield_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='svg_artefact',
            field=models.CharField(default='{}', max_length=256),
        ),
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 21, 50, 8, 800925)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='icon_style',
            field=models.CharField(choices=[('disk', 'Medium disk'), ('coins', 'Three coins')], default='disk', max_length=256),
        ),
    ]
