# Generated by Django 4.0.3 on 2022-04-02 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0070_alter_availability_when_alter_profile_icon_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 23, 59, 21, 750610)),
        ),
    ]
