# Generated by Django 4.0.3 on 2022-04-04 17:57

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0093_alter_availability_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='session',
            name='max_episodes',
        ),
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 4, 4, 19, 57, 2, 208196)),
        ),
        migrations.AlterField(
            model_name='session',
            name='alpha',
            field=colorfield.fields.ColorField(blank=True, default='#666666', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='session',
            name='beta',
            field=colorfield.fields.ColorField(blank=True, default='#666666', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=6),
        ),
        migrations.AlterField(
            model_name='session',
            name='gamma',
            field=colorfield.fields.ColorField(blank=True, default='#666666', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_ready',
            field=models.BooleanField(blank=True, default=False, verbose_name='ok'),
        ),
        migrations.AlterField(
            model_name='session',
            name='level',
            field=models.CharField(blank=True, choices=[('0', 'Débutants'), ('1', 'Tranquille'), ('2', 'Intermédiaire'), ('3', 'Difficile'), ('4', 'Chevronnés')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='session',
            name='newbies_allowed',
            field=models.BooleanField(blank=True, default=True, verbose_name='noobs'),
        ),
        migrations.AlterField(
            model_name='session',
            name='one_shot_adventure',
            field=models.BooleanField(blank=True, default=True, verbose_name='oneshot'),
        ),
        migrations.AlterField(
            model_name='session',
            name='optional_spots',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_start',
            field=models.TimeField(blank=True, default=datetime.time(18, 0)),
        ),
    ]
