# Generated by Django 4.0.3 on 2022-04-04 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0094_remove_session_episode_remove_session_max_episodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 4, 4, 19, 58, 44, 878593)),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
