# Generated by Django 4.0.3 on 2022-04-04 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0095_alter_availability_when_alter_session_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 4, 4, 23, 38, 6, 430453)),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
