# Generated by Django 4.0.3 on 2022-04-05 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0096_alter_availability_when_alter_session_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 4, 5, 11, 21, 12, 77870)),
        ),
    ]
