# Generated by Django 4.0.3 on 2022-04-06 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0114_alter_availability_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 4, 6, 4, 12, 6, 331352)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='icon_style',
            field=models.CharField(choices=[('disk', 'Disque'), ('coins', 'Trois deniers'), ('cross', 'Croix'), ('claws', 'Griffure'), ('diamond', 'Losange'), ('crystal', 'Cristal')], default='disk', max_length=256),
        ),
    ]
