# Generated by Django 4.0.3 on 2022-04-06 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0116_rename_icon_style_profile_iconstyle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 4, 6, 12, 53, 31, 481183)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='realm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.realm'),
        ),
    ]
