# Generated by Django 4.0.3 on 2022-04-06 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0117_alter_availability_when_alter_profile_realm'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weeks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 4, 6, 17, 40, 57, 562212)),
        ),
    ]
