# Generated by Django 4.0.3 on 2022-04-10 12:40

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0122_profile_hair_alter_availability_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 14, 40, 33, 674467)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hair',
            field=colorfield.fields.ColorField(default='#C0A0B0', image_field=None, max_length=18, samples=None),
        ),
    ]
