# Generated by Django 4.0.3 on 2022-04-10 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0123_alter_availability_when_alter_profile_hair'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='full_link',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='availability',
            name='when',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 15, 21, 56, 800583)),
        ),
    ]
