# Generated by Django 4.0.3 on 2022-04-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0133_alter_availability_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date_start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
