# Generated by Django 4.0.3 on 2022-04-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0134_alter_session_date_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='gamma',
        ),
        migrations.RemoveField(
            model_name='session',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='session',
            name='gamma',
        ),
    ]
