# Generated by Django 4.0.3 on 2022-04-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0135_remove_campaign_beta_remove_campaign_gamma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='silhouette',
            field=models.CharField(default='player_base', max_length=256),
        ),
    ]
