# Generated by Django 4.0.3 on 2022-04-15 06:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0136_alter_profile_silhouette'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eyes',
            field=colorfield.fields.ColorField(default='#666666', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hair',
            field=colorfield.fields.ColorField(default='#666666', image_field=None, max_length=18, samples=None),
        ),
    ]
