# Generated by Django 4.0.3 on 2022-04-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0137_profile_eyes_alter_profile_hair'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facestyle',
            field=models.CharField(choices=[('thin', 'Mince'), ('standard', 'Moyen'), ('bold', 'Large')], default='standard', max_length=256),
        ),
    ]
