# Generated by Django 4.0.3 on 2022-04-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0138_profile_facestyle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facestyle',
            new_name='face_style',
        ),
    ]
