# Generated by Django 4.0.3 on 2022-04-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0139_rename_facestyle_profile_face_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='mail_wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
