# Generated by Django 4.0.3 on 2022-04-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0140_profile_mail_sunday_profile_mail_wednesday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hair_style',
            field=models.CharField(choices=[('standard', 'Sans'), ('type1', 'Cheveux 1'), ('type2', 'Cheveux 2')], default='standard', max_length=256),
        ),
        migrations.AddField(
            model_name='profile',
            name='mouth_style',
            field=models.CharField(choices=[('standard', 'Sans'), ('type1', 'Type 1'), ('type2', 'Type 2')], default='standard', max_length=256),
        ),
    ]
