# Generated by Django 4.0.3 on 2022-04-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0142_remove_session_is_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shield',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='silhouette',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='svg_artefact',
        ),
    ]
