# Generated by Django 4.0.3 on 2022-04-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0143_remove_profile_shield_remove_profile_silhouette_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
