# Generated by Django 4.0.3 on 2022-04-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0144_profile_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='optional_spots',
            field=models.PositiveIntegerField(blank=True, default=4),
        ),
    ]
