# Generated by Django 4.0.3 on 2022-04-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0145_alter_session_optional_spots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hair_style',
            field=models.CharField(choices=[('standard', 'Sans'), ('type1', 'Cheveux 1'), ('type2', 'Cheveux 2'), ('type3', 'Cheveux 3'), ('type4', 'Cheveux 4'), ('type5', 'Cheveux 5'), ('type6', 'Cheveux 6')], default='standard', max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mouth_style',
            field=models.CharField(choices=[('standard', 'Sans'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('type3', 'Type 3'), ('type4', 'Type 4'), ('type5', 'Type 5'), ('type6', 'Type 6')], default='standard', max_length=256),
        ),
    ]
