# Generated by Django 4.0.3 on 2022-04-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0147_campaign_full_run_duration_campaign_toc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.game'),
        ),
    ]
