# Generated by Django 4.0.3 on 2022-04-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0148_alter_campaign_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='acronym',
            field=models.CharField(default='', max_length=32),
        ),
    ]
