# Generated by Django 4.0.3 on 2022-04-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0151_session_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_visible',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
