# Generated by Django 4.0.3 on 2022-04-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0152_campaign_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='club',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
