# Generated by Django 4.0.3 on 2022-04-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0153_profile_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail_daily',
            field=models.BooleanField(default=False),
        ),
    ]
