# Generated by Django 4.0.3 on 2022-04-28 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0154_profile_mail_daily'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mail_daily',
            new_name='mail_cyber_postit',
        ),
    ]
