# Generated by Django 4.0.3 on 2022-05-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0156_remove_profile_iconstyle_remove_profile_shieldstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='error_status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
