# Generated by Django 4.0.3 on 2022-08-19 11:03

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0157_session_error_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skin1',
            field=colorfield.fields.ColorField(default='#666666', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='skin2',
            field=colorfield.fields.ColorField(default='#666666', image_field=None, max_length=18, samples=None),
        ),
    ]
