# Generated by Django 4.0.3 on 2022-08-19 11:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0158_profile_skin1_profile_skin2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skin1',
            field=colorfield.fields.ColorField(default='#ffccff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skin2',
            field=colorfield.fields.ColorField(default='#aa88aa', image_field=None, max_length=18, samples=None),
        ),
    ]
