# Generated by Django 4.0.3 on 2022-08-19 12:02

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0159_alter_profile_skin1_alter_profile_skin2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hair_style',
            field=models.CharField(choices=[('standard', 'Sans'), ('type1', 'Cheveux 1'), ('type2', 'Cheveux 2'), ('type3', 'Cheveux 3'), ('type4', 'Cheveux 4'), ('type5', 'Cheveux 5'), ('type6', 'Cheveux 6'), ('type7', 'Cheveux 7')], default='standard', max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skin1',
            field=colorfield.fields.ColorField(default='#CEB090', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skin2',
            field=colorfield.fields.ColorField(default='#9C8267', image_field=None, max_length=18, samples=None),
        ),
    ]
