# Generated by Django 4.0.3 on 2022-09-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0160_alter_profile_hair_style_alter_profile_skin1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tracker_auto',
            field=models.BooleanField(default=False),
        ),
    ]
