# Generated by Django 4.0.3 on 2022-10-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0161_profile_tracker_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
