# Generated by Django 4.0.3 on 2022-11-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0162_campaign_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gaming_in_english',
            field=models.CharField(choices=[('0', 'No way!'), ('1', 'I can try'), ('2', 'Yes!'), ('3', 'Okidoki. I can be gamemaster.')], default='0', max_length=1),
        ),
    ]
