# Generated by Django 4.0.3 on 2022-11-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0163_profile_gaming_in_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2),
        ),
    ]
