# Generated by Django 4.0.3 on 2022-11-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0164_session_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='padid',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hair_style',
            field=models.CharField(choices=[('standard', 'Sans'), ('type1', 'Cheveux 1'), ('type2', 'Cheveux 2'), ('type3', 'Cheveux 3'), ('type4', 'Cheveux 4'), ('type5', 'Cheveux 5'), ('type6', 'Cheveux 6'), ('type7', 'Cheveux 7'), ('type8', 'Cheveux 8'), ('type9', 'Cheveux 9'), ('type10', 'Cheveux 10')], default='standard', max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mouth_style',
            field=models.CharField(choices=[('standard', 'Sans'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('type3', 'Type 3'), ('type4', 'Type 4'), ('type5', 'Type 5'), ('type6', 'Type 6'), ('type7', 'Type 7'), ('type8', 'Type 8'), ('type9', 'Type 9'), ('type10', 'Type 10')], default='standard', max_length=256),
        ),
    ]
