# Generated by Django 4.0.3 on 2022-11-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0166_alter_profile_padid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='face_style',
            field=models.CharField(choices=[('thin', '-1'), ('standard', '0'), ('bold', '1')], default='standard', max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hair_style',
            field=models.CharField(choices=[('standard', '0'), ('type1', '1'), ('type2', '2'), ('type3', '3'), ('type4', '4'), ('type5', '5'), ('type6', '6'), ('type7', '7'), ('type8', '8'), ('type9', '9'), ('type10', '10')], default='standard', max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mouth_style',
            field=models.CharField(choices=[('standard', '0'), ('type1', '1'), ('type2', '2'), ('type3', '3'), ('type4', '4'), ('type5', '5'), ('type6', '6'), ('type7', '7'), ('type8', '8'), ('type9', '9'), ('type10', '10')], default='standard', max_length=256),
        ),
    ]
