# Generated by Django 4.0.3 on 2022-11-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0167_alter_profile_face_style_alter_profile_hair_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='face_style',
            field=models.CharField(choices=[('thin', '0'), ('standard', '1'), ('bold', '2')], default='standard', max_length=256),
        ),
    ]
