# Generated by Django 4.0.3 on 2023-02-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0170_alter_profile_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='episode',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
