# Generated by Django 4.0.3 on 2023-02-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0171_session_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_match',
            field=models.BooleanField(default=False),
        ),
    ]
