# Generated by Django 4.0.3 on 2023-02-17 10:17

import colorfield.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0172_session_is_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('date_start', models.DateField(blank=True, default=None, null=True)),
                ('time_start', models.TimeField(blank=True, default=datetime.time(18, 0))),
                ('duration', models.PositiveIntegerField(blank=True, default=6)),
                ('place', models.CharField(blank=True, default='', max_length=128)),
                ('optional_spots', models.PositiveIntegerField(blank=True, default=4)),
                ('alpha', colorfield.fields.ColorField(blank=True, default='#666666', image_field=None, max_length=18, samples=None)),
                ('wanted', models.CharField(blank=True, default='', max_length=64)),
                ('error_status', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(blank=True, default=False)),
                ('is_match', models.BooleanField(default=False)),
                ('realm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.realm')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
