# Generated by Django 4.0.3 on 2023-02-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0173_spot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='place',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='realm',
        ),
    ]
