# Generated by Django 4.0.3 on 2023-03-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0174_remove_spot_duration_remove_spot_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='code_link',
            field=models.CharField(default='', max_length=64),
        ),
    ]
