# Generated by Django 4.0.3 on 2023-03-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0176_alter_session_code_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='code_link',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
